sudo: required
services:
  - docker

before_install:
  - docker build -t paddy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true paddy/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-deploy"
  environment: "Docker-deploy-env"
  bucket_name: "elasticbeanstalk-eu-west-1-385638670581"
  bucket_path: "docker-deploy"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY